<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration: Create Recommendations Table
 * Description: Stores recommendations generated by the system and reviewed by supervisors,
 * linked to a specific student's weekly follow-up record.
 * Contains automated recommendations and supervisor-approved final recommendations.
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('recommendations', function (Blueprint $table) {
            $table->id();

            // Foreign key: Weekly follow-up reference
            $table->unsignedBigInteger('weekly_followup_id')
                ->comment('Reference to the student weekly follow-up');

            // System-generated recommendation
            $table->text('generated_recommendation')
                ->comment('Recommendation automatically generated by the system based on student performance');

            // Supervisor review and final recommendation
            $table->text('supervisor_recommendation')
                ->nullable()
                ->comment('Final recommendation approved by the supervisor');

            // Foreign key: Supervisor who reviewed - explicit unsignedBigInteger
            $table->unsignedBigInteger('supervisor_id')
                ->nullable()
                ->comment('Supervisor who reviewed and signed the recommendation');

            // Signature timestamp
            $table->timestamp('signed_at')
                ->nullable()
                ->comment('Date and time when the supervisor signed the recommendation');

            // Timestamps
            $table->timestamps();

            // Indexes for performance
            $table->index('weekly_followup_id', 'idx_recommendations_followup');
            $table->index('supervisor_id', 'idx_recommendations_supervisor');
            $table->index('signed_at', 'idx_recommendations_signed');

            // Composite indexes
            $table->index(['supervisor_id', 'signed_at'], 'idx_recommendations_supervisor_signed');
        });

        // Add foreign keys after table creation
        Schema::table('recommendations', function (Blueprint $table) {
            $table->foreign('weekly_followup_id', 'fk_recommendations_followup')
                ->references('id')
                ->on('student_weekly_followups')
                ->onDelete('cascade');

            $table->foreign('supervisor_id', 'fk_recommendations_supervisor')
                ->references('id')
                ->on('teachers')
                ->onDelete('set null');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('recommendations', function (Blueprint $table) {
            $table->dropForeign('fk_recommendations_followup');
            $table->dropForeign('fk_recommendations_supervisor');
        });

        Schema::dropIfExists('recommendations');
    }
};
