<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Recommendation
 * 
 * Stores recommendations generated by the system and reviewed by supervisors,
 * linked to a specific student's weekly follow-up record.
 *
 * ملاحظة: لا يوجد CenterScope هنا عمدًا — جدول recommendations ليس فيه
 * عمود center_id ولا circle_id، والفلترة الصحيحة تتم تلقائيًا عبر
 * علاقة weeklyFollowup (وهي نفسها محمية بـ CenterScope). أي استعلام
 * مباشر على Recommendation في المستقبل يجب أن يمر عبر
 * whereHas('weeklyFollowup') بدلاً من الاعتماد على scope تلقائي.
 */
class Recommendation extends Model
{
    /**
     * The table associated with the model.
     */
    protected $table = 'recommendations';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'weekly_followup_id',
        'generated_recommendation',
        'supervisor_recommendation',
        'supervisor_id',
        'signed_at',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'signed_at' => 'datetime',
    ];

    // ==========================================
    // Relationships
    // ==========================================

    /**
     * Get the weekly follow-up associated with this recommendation.
     */
    public function weeklyFollowup(): BelongsTo
    {
        return $this->belongsTo(StudentWeeklyFollowup::class, 'weekly_followup_id');
    }

    /**
     * Get the supervisor who reviewed this recommendation.
     */
    public function supervisor(): BelongsTo
    {
        return $this->belongsTo(Teacher::class, 'supervisor_id');
    }
}
